# Generated by Django 4.2.3 on 2024-03-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("domain", models.CharField(max_length=100)),
                ("goals", models.TextField()),
            ],
            options={
                "db_table": "ContactDetails",
            },
        ),
        migrations.CreateModel(
            name="IT_Companies",
            fields=[
                ("company_id", models.IntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("imagepath", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "it_Companies",
            },
        ),
        migrations.CreateModel(
            name="signup",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "signup",
            },
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                ("desc_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("job_location", models.CharField(max_length=255)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("years_of_experience", models.IntegerField()),
                ("required_tech_stack", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_job_portal.it_companies",
                    ),
                ),
            ],
            options={
                "db_table": "JobDescription",
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("cover_letter", models.TextField()),
                ("resume", models.FileField(upload_to="resumes/")),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_job_portal.jobdescription",
                    ),
                ),
            ],
            options={
                "db_table": "JobApplication",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("feedback_text", models.TextField()),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_job_portal.signup",
                    ),
                ),
            ],
            options={
                "db_table": "Feedback",
            },
        ),
    ]
