# Generated by Django 4.2.3 on 2024-03-29 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_job_portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="it_companies",
            table="IT_Companies",
        ),
    ]
