# Generated by Django 4.2.3 on 2024-03-29 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_job_portal", "0002_alter_it_companies_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactdetails",
            table="ContactDetails",
        ),
    ]
