# Generated by Django 4.2.3 on 2024-03-29 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_job_portal", "0004_alter_contactdetails_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactdetails",
            table="ContactDetails",
        ),
    ]
